### ISSUE TITLE
Is this the repo belonging to the PyPI package? Add link to PyPI

### ISSUE THREAD

**Issue by vollkorn1982** [wiktor-k/pysequoia#1]
Same author, same name, but the PyPI package has been last updated on February 1st and this repo's last commit is from November 2022.

https://pypi.org/project/pysequoia/

Would it be possible to keep them in sync and also to put a link to the currently used repo as homepage of the package on PyPI?

**Comment by wiktor-k** [comment]
Yeah, good point. To be honest I'm trying out a couple of forges and didn't settle on one yet. I also didn't get notifications from your issues which is weird because I'm watching my own repo.

Give me some time to sort out the issues and also take care of the bug you reported. And sorry for the noise, the project is still young and in development :bow:

**Comment by vollkorn1982** [comment]
Hi @wiktor-k thanks for syncing the repo. I think adding a link to the repo on the PyPI page would be a good thing. (Left side menu on https://pypi.org/project/pysequoia/ )

**Comment by wiktor-k** [comment]
It will be there when I release a new version. Sorry for closing prematurely!

(see https://github.com/wiktor-k/pysequoia/blob/main/pyproject.toml#L24)
